---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: mclaren
  labels:
    name: helloworld
spec:
  type: LoadBalancer
  selector:
    name: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
